spring:
  application:
    name: demo-openforeign
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12562903
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1200000
      auto-commit: true
      pool-name: HikariPool-CP

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect